### ISSUE TITLE
Install script fails when installing escualo

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-devinstaller#6]
If you run the installer, it fails with the next error in [this line](https://github.com/mumuki/mumuki-development-installer/blob/master/install.sh#L52)

```bash
[MumukiDevelopmentInstaller] Provisioning the Vagrant VM....
Fetching: escualo-0.5.1.gem (100%)
Successfully installed escualo-0.5.1
Parsing documentation for escualo-0.5.1
Installing ri documentation for escualo-0.5.1
Done installing documentation for escualo after 0 seconds
1 gem installed
/home/federico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:442:in `run_active_command': invalid command (Commander::Runner::InvalidCommandError)
	from /home/federico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /home/federico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /home/federico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'

```

This issue may be related with the fact that nowadys escualo last version is 3.0.2, but the installer use version 0.5.1.

**Comment by flbulgarelli** [comment]
It is ok that the installer uses an old version, since new versions don't provide script command. That should not be the problem.

**Comment by flbulgarelli** [comment]
However, we definitely could update the installer in order to use newer escualo versions AND replace old scripts with just a bash script. E.g:

_change this_

```yaml
local:
 - bootstrap --no-monit --with-rbenv --env development --verbose
remote:
 - env set PGDATABASE=atheneum
           POSTGRESQL_DB_USERNAME=mumuki
           POSTGRESQL_DB_PASSWORD=mumuki
           POSTGRESQL_DB_HOST=localhost
 - plugin install postgre --verbose
 - plugin install docker --verbose
 - plugin install rabbit --rabbit-admin-password admin --verbose
 - plugin install mongo --verbose
```

_into this_

```bash
escualo bootstrap --no-monit --with-rbenv --env development --verbose
escualo env set PGDATABASE=atheneum \
                          POSTGRESQL_DB_USERNAME=mumuki \
                          POSTGRESQL_DB_PASSWORD=mumuki \
                          POSTGRESQL_DB_HOST=localhost
escualo plugin install postgre --verbose
escualo plugin install docker --verbose
escualo plugin install rabbit --rabbit-admin-password admin --verbose
escualo plugin install mongo --verbose
```

**Perhaps, by updating to latest escualo version, the original error will get magically solved** :sweat_smile:
